ICLDisco/dplasma

tests/testing_zpotrf_dtd.c
Change references to PARSEC_HAVE_CUDA to DPLASMA_HAVE_CUDA (one may
configure DPLASMA to not have cuda even when parsec has it)
Signed-off-by: Aurelien Bouteiller <bouteill@icl.utk.edu>
=> dtd:cuda: adapt the zpotrf_dtd test to the new gpu_device API

CMakeLists.txt
After a fresh git clone, the PaRSEC submodule would track master rather than the validated SHA
=> After a fresh git clone, the PaRSEC submodule would track master rather than the validated SHA

contrib/platforms/macosx
config: macosx: bison 3 is needed, and Veclib doesn't have LAPACKE
Change defaults so that we try to pick Brew options
Signed-off-by: Aurélien Bouteiller <bouteill@icl.utk.edu>
=> config: macosx: bison 3 is needed, and Veclib doesn't have LAPACKE

cmake_modules/DplasmaCompilerFlags.cmake
Signed-off-by: Aurélien Bouteiller <bouteill@icl.utk.edu>
=> Missing include in cmake fortran compiler flag checker

tests/common.c
As discussed in the Monday meeting, this small inconsistently led to some larger scale confusion trying to get results. Proposition to remove passing arguments to dplasma like:
`./tests/testing_dgemm 1000`
And forcing them to be in the form:
`./tests/testing_dgemm -N 1000`
(also removed someone's commented out debugging print statement)
=> modify dplasma so that passing naked N no longer works.

.github/workflows/build_cmake.yml
Provide a temporary solution to https://github.com/ICLDisco/parsec/issues/548 by disabling the RECURSIVE device in test mode.
=> Temporarily disable RECURSIVE device in CI test mode

src/scalapack_wrappers/dplasma_wrapper_pdgemm.c, src/scalapack_wrappers/dplasma_wrapper_pdgetrf_1d.c, src/scalapack_wrappers/dplasma_wrapper_pdgetrf_nopiv.c, src/scalapack_wrappers/dplasma_wrapper_pdlatsqr.c, src/scalapack_wrappers/dplasma_wrapper_pdpotrf.c, src/scalapack_wrappers/dplasma_wrapper_pdtrmm.c, src/scalapack_wrappers/dplasma_wrapper_pdtrsm.c
Make dplasma scalapack wrappers compile with MPICH
=> Do not cast MPI communicators to void*, this is incompatible with MPICH

src/dplasmajdf_lapack_dtt.h, src/include/dplasma/types_lapack.h, src/utils/dplasma_arena_datatype.h, src/utils/dplasma_lapack_adtt.c, src/utils/dplasma_lapack_adtt.h
This is a first step toward protecting access to the arena info hash
table, the one allowing us to correctly reuse datatypes and their arena.
While this patch should work, it might be overly costly, as all accesses
are now protected, and I don't think we need this. Indeed, the arena are
build during the creation of a taskpool, so by the time any of the
threads are using them, they exist for a long time. Thus, the only
portion we need to protect is when multiple threads, mostly in the
context of recursive calls are creating new taskpool for submatrices,
and they create types that can be reused.
Signed-off-by: George Bosilca <bosilca@icl.utk.edu>
=> Protect accesses to the data info and arena.

src/utils/dplasma_lapack_adtt.c
fix: adt structure passed by value accessed as a pointer in scalapack wrapper verbose debug
=> fix: adt structure passed by value accessed as a pointer in scalapack

tests/testing_zgemm_dtd.c, tests/testing_zgeqrf_dtd.c, tests/testing_zgeqrf_dtd_untied.c, tests/testing_zgetrf_incpiv_dtd.c, tests/testing_zpotrf_dtd_untied.c
bugifx: dtd would do del2arena after releasing the corresponding adt, which would randomly crash.
as seen in CI build #181 https://github.com/ICLDisco/dplasma/actions/runs/6631295204/job/18014509921
=> bugifx: dtd would do del2arena after releasing the corresponding adt,

src/zgeqrf.jdf, src/zpotrf_L.jdf, src/zpotrf_U.jdf
Silence warnings about having the recursive callbacks defined when parsec does not have RECURSIVE_DEV_SUPPORT
=> Silence warnings about having the recursive callbacks defined

src/zpotrf_L.jdf, src/zpotrf_U.jdf
Consistent ordering of RECURSIVE/CUDA bodies: CUDA first, recursive second.
This ordering is consistent with existing ordering in zgeqrf, and most kernels in zpotrf (except for po_po); this will prefer using GPU kernels if available, and fallback to recursive if load balancer lets a kernel fallback to CPU.
=> Consistent ordering of RECURSIVE/CUDA bodies: CUDA first, recursive

src/zpotrf_L.jdf, src/zpotrf_U.jdf
cleanup: some weight properties were leftover
because they had a typo "weigth" and were not found by search-replace
=> cleanup: some weight properties were leftover

tests/common.c, tests/common.h
=> Use new feature parsec_devices_print_stats to print per-tp stats

tests/Testings.cmake
parsec https://github.com/ICLDisco/parsec/pull/633)
=> ci: run with GPUs only when specifically requested in ctest (same as

tests/testing_zgemm.c, tests/testing_zgemm_dtd.c, tests/testing_zgeqrf.c, tests/testing_zgeqrf_dtd.c, tests/testing_zgeqrf_dtd_untied.c, tests/testing_zpoinv.c, tests/testing_zpotrf.c, tests/testing_zpotrf_dtd.c, tests/testing_zpotrf_dtd_untied.c
We would skip the warmup of device 1 in some cases.
=> When recursive is disabled, first gpu is at index 1

src/dplasmaaux_cuda.h, src/dplasmaaux_hip.h, src/dtd_wrappers/zgemm.c, src/dtd_wrappers/zherk.c
They would cause compilation error when used as functions (e.g. as parameters in a cublass kernel) due to having semicolons etc. Reworded so that they operate as functions (not made them inline because that would cause pulling a bunch of includes when not used.
=> The macros to convert trans/notrans etc were not correct for use inline

tests/common.c
otherwise it prints DPLAMA_ERR_NOT_INITIALIZED as the number of available gpus
=> gpu: when gpu is not compiled it, we need to reset the iparam NGPU to 0

src/dplasmaaux.c, src/dplasmaaux.h, src/zlascal_wrapper.c, src/zlaset_wrapper.c, src/zlatms_wrapper.c, src/zplghe_wrapper.c, src/zplgsy_wrapper.c, src/zplrnt_wrapper.c, src/zpltmg_wrapper.c, tests/testing_zgemm.c, tests/testing_zpotrf.c
These are the performance comparisons.
I changed to Lower in Cholesky testing and will create an issue to track why Upper behaves differently.
=> Add parsec_advise_data_on_device for zpotrf_L

tests/common.c, tests/common.h, tests/testing_zgeadd.c, tests/testing_zhebut.c, tests/testing_zheev.c, tests/testing_zhemm.c, tests/testing_zher2k.c, tests/testing_zherk.c, tests/testing_zlange.c, tests/testing_zpoinv.c, tests/testing_zposv.c, tests/testing_zpotrf.c, tests/testing_zpotrf_dtd.c, tests/testing_zpotrf_dtd_untied.c, tests/testing_zprint.c, tests/testing_zsymm.c, tests/testing_zsyr2k.c, tests/testing_zsyrk.c, tests/testing_ztrmm.c, tests/testing_ztrsm.c, tests/testing_ztrtri.c, tests/testing_zunmlq.c, tests/testing_zunmlq_hqr.c, tests/testing_zunmlq_systolic.c, tests/testing_zunmqr.c, tests/testing_zunmqr_hqr.c, tests/testing_zunmqr_systolic.c
also there was a name conflict between the uplo variable being an int in some testers, and an array of two ints in some other testers, I pluralized the arrays. 
fixes: #130
=> Add --uplo command line parameter, use lower by default in all cases

.github/CI/spack_setup.sh, .github/workflows/build_cmake.yml, CMakeLists.txt
OK to merge now if you are OK with the failing NVIDIA test.
=> Refactoring CI

src/zgemm_NN_gpu.jdf, src/zgemm_wrapper.c, tests/common.h, tests/testing_zgemm.c
=> The Gemm NN GPU is missing declaration of datatype #138
